controller_list:
  - name: fake_arm_FR_controller
    type: $(arg fake_execution_type)
    joints:
      - BaseBody_to_Subsystem11
      - Subsystem11_to_Subsystem12
      - Subsystem12_to_Subsystem13
      - Subsystem13_to_Subsystem14
  - name: fake_base_controller
    type: $(arg fake_execution_type)
    joints:
      - world_to_BaseBody
initial:  # Define initial robot poses per group
#  - group: arm_FR
#    pose: home

  []