arm_FR_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - BaseBody_to_Subsystem11
    - Subsystem11_to_Subsystem12
    - Subsystem12_to_Subsystem13
    - Subsystem13_to_Subsystem14
  gains:
    BaseBody_to_Subsystem11:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Subsystem11_to_Subsystem12:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Subsystem12_to_Subsystem13:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Subsystem13_to_Subsystem14:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
base_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - world_to_BaseBody
  gains:
    world_to_BaseBody:
      p: 100
      d: 1
      i: 1
      i_clamp: 1