#goal definition
float64 simulation_time
float64 integration_stepsize
float64 datasave_stepsize
float64 gravity
std_msgs/String analysis_method
std_msgs/String solver
float64[3] gravity_axis
float64[3] rotational_axis
float64[3] translational_axis
---
#result definition
bool complete
---
#feedback
float64 time_current
float64 percent_complete