#goal definition
float32 simulation_time
float32 integration_stepsize
std_msgs/String analysis_method
std_msgs/String solver
float32 gravity
float32[3] gravity_axis
float32[3] rotational_axis
float32[3] translational_axis
---
#result definition
bool complete
---
#feedback
float32 time_current
float32 percent_complete
